### ISSUE TITLE
Need help to port to ATmega328PB

### ISSUE THREAD

**Issue by thorstad** [nayem-cosmic/RFM69-Library-AVR#2]
Hi, I need help to make it work for ATmega328PB in Atmel Studio, pure C code.
I get alots of error and don't really know how to solve them, thanks!
![image](https://user-images.githubusercontent.com/40394559/41809949-2799fa60-76f6-11e8-98b2-1ef6201f22ad.png)

![image](https://user-images.githubusercontent.com/40394559/41809985-cea4f4ea-76f6-11e8-87fc-46a7d941e508.png)

Im using PB1 as Interrupt, PB2 SS, PB3 Mosi, PB4 Miso and PB5 Sck.

**Comment by thorstad** [comment]
Ok, I got it to compile now with no errors, I moved everything to the RFM9.c so all is good, but I have not yet tested if it work, will do it now.

**Comment by aliznayem** [comment]
OK. If you have any problem. Let me know.
Best Regards.

**Comment by thorstad** [comment]
After removing them and re-adding them I had no problem with compiling them after I change the ports I believe is on the Atmega328PB, but when I run the code it just stops.
Here are the pinouts:
```
#define SS_DDR               DDRB
#define SS_PORT              PORTB
#define SS_PIN               DDRB2

#define INT_DDR              DDRB
#define INT_PORT	     PORTB
#define INT_PIN		     DDRB1
#define INTn                  INT0
#define ISCn0                ISC10
#define ISCn1                ISC11
#define INT_VECT         INT0_vect

#define SPI_DDR   DDRB

#define MISO         DDB4
#define MOSI         DDB3
#define SCK          DDB5
#define SS           DDB2
```
And here are the spi codes:

```
void spi_init()
// Initialize pins for spi communication
{

	DDRB |= (1 << DDB5) | (1 << DDB3) | (1 << DDB2);		//Set SS, MOSI, SCK as Output
	SPCR0 |= (1 << SPE) | (1 << MSTR);

	SPSR0 = (1<<SPI2X);              // Double Clock Rate
	
}

void spi_transfer_sync (uint8_t * dataout, uint8_t * datain, uint8_t len)
// Shift full array through target device
{
	uint8_t i;
	for (i = 0; i < len; i++) {
		SPDR0 = dataout[i];
		while((SPSR0 & (1<<SPIF))==0);
		datain[i] = SPDR0;
	}
}

void spi_transmit_sync (uint8_t * dataout, uint8_t len)
// Shift full array to target device without receiving any byte
{
	uint8_t i;
	for (i = 0; i < len; i++) {
		SPDR0 = dataout[i];
		while((SPSR0 & (1<<SPIF))==0);
	}
}

uint8_t spi_fast_shift (uint8_t data)
// Clocks only one byte to target device and returns the received one
{
	SPDR0 = data;
	while((SPSR0 & (1<<SPIF))==0);
	return SPDR0;
}
```
In the rfm_init:

```
spi_init();                // spi initialize
SS_DDR |= 1<<SS_PIN;       // setting SS as output
SS_PORT |= 1<<SS_PIN;      // setting slave select high
INT_DDR &= ~(1<<INT_PIN);  // setting interrupt pin input. no problem if not given
INT_PORT &= ~(1<<INT_PIN); // setting pull down. because rising will cause interrupt. external pull down is needed.

EICRA |= (1<<ISCn1)|(1<<ISCn0); // setting INTn rising. details datasheet p91. must change with interrupt pin.
EIMSK |= 1<<INTn;               // enable INTn
inISR = 0;
sei(); 
```
I believe the pinouts are a bit wrong, I do not what is the correct one for ATmega328PB.

**Comment by twilco** [comment]
@thorstad What is going wrong, exactly?  Here is the [pinout](https://goo.gl/images/F4AH6Q) and the [datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/40001906A.pdf) for the ATMega328PB.

If you need another example, check out the C++ library this C library is based on: https://github.com/LowPowerLab/RFM69/blob/master/RFM69.cpp

Alternatively, you could check out my avr-rf-transmitter project.  It's still a work-in-progress, and the README is out of date, but maybe it will help.  https://github.com/twilco/avr-rf-transmitter

**Comment by aliznayem** [comment]
I think your interrupt pin should be PD2 or PD3.
```
#define INT_DDR       DDRD
#define INT_PORT     PORTD
#define INT_PIN        DDB2
```

**Comment by ytsou1230** [comment]
I am trying to use RFM69 with ATmega328P, but it keep on stuck in this loop when initializing.

while (readReg(REG_SYNCVALUE1) != 0xaa)
    {
        writeReg(REG_SYNCVALUE1, 0xaa);
    }

SPI read is working as I can read register value from RFM69, but SPI write is not working.

Can you please help me with this?

**Comment by ciphermaster** [comment]
Hi,

the issue is, that the files are in UNIX-Format using UNIX-Encoding.
You can use unix2dos.exe available under:

https://waterlan.home.xs4all.nl/dos2unix.html

To convert the files. Just do an 

unix2dos *.c
unix2dos*.h

and then it sould work. Hope this helps.
