### ISSUE TITLE
Bug in encryption setup

### ISSUE THREAD

**Issue by dilo83** [nayem-cosmic/RFM69-Library-AVR#4]
Encryption is not working. I checked source from LowPowerLab and found one difference:

RFM69.c, void encrypt(const char* key), line 286-287:
```
else
  writeReg(REG_PACKETCONFIG2, (readReg(REG_PACKETCONFIG2) & 0xFE) | 0x00); 
```

must be:
```
//else - no else, enable or disable on key
  writeReg(REG_PACKETCONFIG2, (readReg(REG_PACKETCONFIG2) & 0xFE) | (key?1:0));
```

...now it's working fine.

**Comment by aliznayem** [comment]
Thanks. I have committed the change.
