### ISSUE TITLE
too few arguments to function 'sendACK'	Error in example

### ISSUE THREAD

**Issue by sachooo** [nayem-cosmic/RFM69-Library-AVR#5]
if(ACKRequested())
	sendACK();

In example gives compilation error.

Error	:	too few arguments to function 'sendACK'

**Comment by aliznayem** [comment]
Currently, I am not active in firmware projects. So I do not have any rig to check the error. As far as I remember, it worked on cpp compiler. By the way I can suggest you following solution.

Here is the definition of the function:
void sendACK(const void* buffer, uint8_t bufferSize)

First argument is an array. You can put a blank array in it. 
Second argument is the length of array you put as the first argument. Pass 0 in it.
