### ISSUE TITLE
Ported to Attiny84

### ISSUE THREAD

**Issue by stenfalp** [nayem-cosmic/RFM69-Library-AVR#6]
[RFM69_c_diff.txt](https://github.com/nayem-cosmic/RFM69-Library-AVR/files/4638042/RFM69_c_diff.txt)
[RFM69_h_diff.txt](https://github.com/nayem-cosmic/RFM69-Library-AVR/files/4638043/RFM69_h_diff.txt)

Hi,

I have ported it to Attiny84. Initially the receiver which was using the LowPowerLab library wasn't receiving anything. I've have made some changes to your code to make it work. 
Apparently there was an off-by-one error. LowPowerLab has changed the library a bit and I updated your code accordingly (only the sending part).

Attached the unified diff.

**Comment by aliznayem** [comment]
Hello!
Currently, I am not active in microcontroller projects. So I don't have any rig to test changes. Please feel free to create a pull request. I will merge that.
