### ISSUE TITLE
Testing in Arduino IDE

### ISSUE THREAD

**Issue by klerone** [nayem-cosmic/RFM69-Library-AVR#7]
Hello @nayem-cosmic 

I am trying to use your library in the Arduino IDE in the hope to use it with the Attiny84, I did the following:

- Change *.c  files to *.cpp
- also renamed to avoid conflicts.
- testing a basic sketch just including the libraries.

when I compile I get this errors when compile for atmega328

> sketch\src\RFM69-AVR-C\RFM69avr.cpp.o:(.bss.DATA+0x0): multiple definition of `DATA'
sketch\Test_RFM_AVR-C.ino.cpp.o:(.bss.DATA+0x0): first defined here
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board ATmega328

I read it can be something related to the millis() function or timer, but I do not really understand that much. I hope you can point in the right direction where to look.

Thank you in advance.

**Comment by aliznayem** [comment]
Hi!
Why don't you use original [LowPowerLab](https://github.com/LowPowerLab/RFM69) library for Arduino IDE.

**Comment by klerone** [comment]
That one is too big to the attiny84, I have tried but the RAM fall short very fast and will not work properly. Can be used as Receiver but when use to transmit data will not work at all.

**Comment by aliznayem** [comment]
This library is same as LowPowerLab, just adopted to AVR environment. If you use this library in Arduino IDE, should not work.

**Comment by aliznayem** [comment]
If you burn this firmware through any AVR IDE, RAM may fall short also for Attiny84. There is no difference in memory allocation between LowPowerLab and this library.

**Comment by klerone** [comment]
Understood, then I may upgrade to an atmega328. Thanks for your time.

**Comment by aliznayem** [comment]
My pleasure!
